"""
Command-line interface for enterprise-claude-kit.

Entry point: ecl (configured in pyproject.toml)
Uses Typer for CLI framework and Rich for beautiful terminal output.
"""
from __future__ import annotations

import asyncio
import os
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Annotated, Any

import typer
from dotenv import load_dotenv
from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table
from rich.text import Text

load_dotenv()

app = typer.Typer(
    name="ecl",
    help="enterprise-claude-kit CLI — governed AI at scale",
    rich_markup_mode="rich",
    no_args_is_help=True,
)
agents_app = typer.Typer(help="Manage Claude agents", no_args_is_help=True)
app.add_typer(agents_app, name="agents")

console = Console()
err_console = Console(stderr=True, style="bold red")

# ---------------------------------------------------------------------------
# Module-level constants resolved from env at import time
# ---------------------------------------------------------------------------

_DEFAULT_AUDIT_DB: str = os.environ.get("ECL_AUDIT_DB", "./audit.db")
_DEFAULT_MONITOR_DB: str = os.environ.get("ECL_MONITOR_DB", "./monitor.db")
_DEFAULT_BUDGET_USD: float = float(os.environ.get("ECL_DAILY_BUDGET_USD", "100.0"))

# ---------------------------------------------------------------------------
# Scaffold templates
# ---------------------------------------------------------------------------

_ENV_EXAMPLE = """\
# enterprise-claude-kit — environment variables
# Copy this file to .env and fill in your values.

# ── Anthropic ─────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY=sk-ant-...

# ── Database paths ────────────────────────────────────────────────────────────
ECL_AUDIT_DB=./audit.db
ECL_MONITOR_DB=./monitor.db

# ── Budget & cost controls ────────────────────────────────────────────────────
ECL_DAILY_BUDGET_USD=100.0
ECL_ALERT_THRESHOLD_PCT=0.8

# ── Governance ────────────────────────────────────────────────────────────────
ECL_PII_FILTER=true
ECL_GXP_MODE=false
ECL_MAX_PROMPT_LENGTH=100000
ECL_REQUIRE_SYSTEM_PROMPT=true
ECL_CONSTITUTIONAL_AI=true
# Comma-separated list of blocked keywords (leave blank for none)
ECL_BLOCKED_KEYWORDS=

# ── Adoption / wave management ────────────────────────────────────────────────
ECL_WAVE_DB=./waves.db

# ── MCP connectors ────────────────────────────────────────────────────────────
# GitHub
GITHUB_TOKEN=ghp_...
# Jira
JIRA_URL=https://yourorg.atlassian.net
JIRA_EMAIL=you@example.com
JIRA_API_TOKEN=...
# Slack
SLACK_BOT_TOKEN=xoxb-...
# Confluence
CONFLUENCE_URL=https://yourorg.atlassian.net/wiki
CONFLUENCE_EMAIL=you@example.com
CONFLUENCE_API_TOKEN=...
# SharePoint / Microsoft
SHAREPOINT_CLIENT_ID=...
SHAREPOINT_CLIENT_SECRET=...
SHAREPOINT_TENANT_ID=...
"""

_ECL_CONFIG_YAML = """\
# enterprise-claude-kit — project configuration
# Generated by: ecl init

governance:
  pii_filter: true
  gxp_mode: false
  max_prompt_length: 100000
  require_system_prompt: true
  constitutional_ai: true
  blocked_keywords: []
  log_violations: true

monitor:
  daily_budget_usd: 100.0
  alert_threshold_pct: 0.8
  db_path: ./monitor.db
  reclaim_inactive_after_days: 7

audit:
  db_path: ./audit.db
  gxp_mode: false

waves:
  - id: wave-1
    name: Pilot
    target_personas: [analyst]
    target_count: 10
    activated_count: 0
    start_date: "2025-01-01"
    status: planned

  - id: wave-2
    name: Early Adopters
    target_personas: [analyst, developer]
    target_count: 100
    activated_count: 0
    start_date: "2025-03-01"
    status: planned

  - id: wave-3
    name: General Availability
    target_personas: [analyst, developer, manager]
    target_count: 1000
    activated_count: 0
    start_date: "2025-06-01"
    status: planned

connectors:
  enabled: [github, jira, slack, confluence, sharepoint]
"""

# ---------------------------------------------------------------------------
# Built-in connector registry (used when mcp_connectors module is unavailable)
# ---------------------------------------------------------------------------

_CONNECTOR_REGISTRY: list[dict[str, Any]] = [
    {
        "name": "github",
        "description": "Read/write GitHub issues, PRs, and code",
        "auth_type": "PAT",
        "required_env": ["GITHUB_TOKEN"],
        "tags": ["code", "devops"],
    },
    {
        "name": "jira",
        "description": "Query and update Jira issues and sprints",
        "auth_type": "API Token",
        "required_env": ["JIRA_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"],
        "tags": ["project-management"],
    },
    {
        "name": "slack",
        "description": "Send messages and read Slack channels",
        "auth_type": "Bot Token",
        "required_env": ["SLACK_BOT_TOKEN"],
        "tags": ["communication"],
    },
    {
        "name": "confluence",
        "description": "Search and retrieve Confluence pages",
        "auth_type": "API Token",
        "required_env": ["CONFLUENCE_URL", "CONFLUENCE_EMAIL", "CONFLUENCE_API_TOKEN"],
        "tags": ["knowledge-base"],
    },
    {
        "name": "sharepoint",
        "description": "Access SharePoint document libraries via MSAL OAuth2",
        "auth_type": "OAuth2 (MSAL)",
        "required_env": [
            "SHAREPOINT_CLIENT_ID",
            "SHAREPOINT_CLIENT_SECRET",
            "SHAREPOINT_TENANT_ID",
        ],
        "tags": ["documents", "microsoft"],
    },
]

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _require_api_key() -> str:
    """Return ``ANTHROPIC_API_KEY`` or exit with a helpful error."""
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        err_console.print(
            "[bold red]ANTHROPIC_API_KEY is not set.[/bold red]\n"
            "Run [bold]ecl init[/bold], fill in your .env file, then retry."
        )
        raise typer.Exit(code=1)
    return key


def _bool_env(name: str, default: str = "true") -> bool:
    """Read an env var as a boolean (true/1/yes)."""
    return os.environ.get(name, default).lower().strip() in ("1", "true", "yes")


# ---------------------------------------------------------------------------
# ecl init
# ---------------------------------------------------------------------------


@app.command()
def init(
    directory: Annotated[
        Path,
        typer.Option("--dir", "-d", help="Target directory (default: current directory)"),
    ] = Path("."),
) -> None:
    """Scaffold .env.example and ecl_config.yaml in the target directory."""
    directory = directory.resolve()
    directory.mkdir(parents=True, exist_ok=True)

    env_path = directory / ".env.example"
    config_path = directory / "ecl_config.yaml"

    created: list[str] = []
    skipped: list[str] = []

    for path, content in [(env_path, _ENV_EXAMPLE), (config_path, _ECL_CONFIG_YAML)]:
        if not path.exists():
            path.write_text(content, encoding="utf-8")
            created.append(str(path))
        else:
            skipped.append(str(path))

    if skipped:
        for s in skipped:
            console.print(f"[yellow]⚠  Skipped (already exists):[/yellow] {s}")

    next_steps = (
        "1. [bold]cp .env.example .env[/bold]\n"
        "2. Set [cyan]ANTHROPIC_API_KEY[/cyan] and any connector credentials\n"
        "3. Review [cyan]ecl_config.yaml[/cyan] — adjust budget, governance, and wave schedule\n"
        "4. Run [bold]ecl governance check[/bold] to validate your configuration"
    )

    lines: list[str] = ["[bold green]✅ Enterprise Claude Kit initialized![/bold green]\n"]
    if created:
        lines.append("[bold]Files created:[/bold]")
        for f in created:
            lines.append(f"  • {f}")
        lines.append("")
    lines.append("[bold]Next steps:[/bold]")
    lines.append(next_steps)

    console.print(
        Panel(
            "\n".join(lines),
            title="[bold cyan]enterprise-claude-kit[/bold cyan]",
            border_style="cyan",
            padding=(1, 2),
        )
    )


# ---------------------------------------------------------------------------
# ecl agents list
# ---------------------------------------------------------------------------


@agents_app.command("list")
def agents_list() -> None:
    """List all agents seen in the audit log with call and cost stats."""

    async def _run() -> tuple[list[dict[str, Any]], dict[str, float]]:
        import aiosqlite

        agents_data: list[dict[str, Any]] = []
        if Path(_DEFAULT_AUDIT_DB).exists():
            async with aiosqlite.connect(_DEFAULT_AUDIT_DB) as db:
                db.row_factory = aiosqlite.Row
                async with db.execute(
                    """
                    SELECT
                        agent_id,
                        persona,
                        model_used          AS model,
                        COUNT(*)            AS total_calls,
                        MAX(timestamp)      AS last_active
                    FROM audit_events
                    GROUP BY agent_id, persona, model_used
                    ORDER BY last_active DESC
                    """
                ) as cur:
                    async for row in cur:
                        agents_data.append(dict(row))

        cost_by_agent: dict[str, float] = {}
        if Path(_DEFAULT_MONITOR_DB).exists():
            async with aiosqlite.connect(_DEFAULT_MONITOR_DB) as db:
                db.row_factory = aiosqlite.Row
                async with db.execute(
                    "SELECT agent_id, SUM(cost_usd) AS total "
                    "FROM usage_records GROUP BY agent_id"
                ) as cur:
                    async for row in cur:
                        cost_by_agent[row["agent_id"]] = round(row["total"] or 0.0, 6)

        return agents_data, cost_by_agent

    try:
        agents_data, cost_by_agent = asyncio.run(_run())
    except Exception:  # noqa: BLE001
        console.print_exception()
        raise typer.Exit(code=1)

    if not agents_data:
        console.print(
            Panel(
                "[cyan]No agents have been deployed yet.[/cyan]\n\n"
                "Run [bold]ecl agents deploy <name>[/bold] to create your first agent.",
                title="Agents",
                border_style="blue",
                padding=(1, 2),
            )
        )
        return

    table = Table(
        title="Deployed Agents",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    table.add_column("Agent ID", style="dim", max_width=16)
    table.add_column("Persona")
    table.add_column("Model")
    table.add_column("Status")
    table.add_column("Calls", justify="right")
    table.add_column("Cost USD", justify="right")
    table.add_column("Last Active")

    for agent in agents_data:
        agent_id: str = agent["agent_id"]
        short_id = (agent_id[:12] + "…") if len(agent_id) > 13 else agent_id
        cost = cost_by_agent.get(agent_id, 0.0)

        last_ts: str = agent.get("last_active") or ""
        try:
            last_dt = datetime.fromisoformat(last_ts)
            last_str = last_dt.strftime("%Y-%m-%d %H:%M")
        except (ValueError, AttributeError):
            last_str = last_ts or "—"

        status_text = Text("● active", style="green")

        table.add_row(
            short_id,
            agent["persona"],
            agent["model"],
            status_text,
            str(agent["total_calls"]),
            f"${cost:.4f}",
            last_str,
        )

    console.print(table)


# ---------------------------------------------------------------------------
# ecl agents deploy
# ---------------------------------------------------------------------------


@agents_app.command("deploy")
def agents_deploy(
    name: str,
    config: Annotated[
        Path | None,
        typer.Option("--config", "-c", help="Path to agent YAML config file"),
    ] = None,
    persona: Annotated[str, typer.Option("--persona", help="Agent persona label")] = "default",
    system_prompt: Annotated[
        str,
        typer.Option("--system-prompt", help="System prompt for the agent"),
    ] = "You are a helpful AI assistant.",
    model_tier: Annotated[
        str,
        typer.Option("--tier", help="Model tier: default | batch | gated"),
    ] = "default",
) -> None:
    """Deploy a new governed agent (from CLI flags or a YAML config file)."""
    api_key = _require_api_key()

    # Merge config file values when provided
    if config is not None:
        if not config.exists():
            err_console.print(f"Config file not found: {config}")
            raise typer.Exit(code=1)
        try:
            import yaml

            raw: dict[str, Any] = yaml.safe_load(config.read_text(encoding="utf-8")) or {}
            name = raw.get("name", name)
            persona = raw.get("persona", persona)
            system_prompt = raw.get("system_prompt", system_prompt)
            model_tier = raw.get("model_tier", model_tier)
        except ImportError:
            console.print(
                "[yellow]PyYAML not installed; config file options are ignored.[/yellow]"
            )
        except Exception as exc:
            err_console.print(f"Failed to parse config file: {exc}")
            raise typer.Exit(code=1) from exc

    async def _run() -> tuple[str, str]:
        from enterprise_claude.audit import AuditLogger
        from enterprise_claude.orchestrator import AgentOrchestrator
        from enterprise_claude.token_monitor import MonitorConfig, TokenMonitor

        monitor = TokenMonitor(
            config=MonitorConfig(
                daily_budget_usd=_DEFAULT_BUDGET_USD,
                db_path=_DEFAULT_MONITOR_DB,
            )
        )
        audit_log = AuditLogger(db_path=_DEFAULT_AUDIT_DB)
        orch = AgentOrchestrator(
            api_key=api_key,
            monitor=monitor,
            audit_logger=audit_log,
        )
        await orch.initialize()
        agent = await orch.create_agent(
            name=name,
            system_prompt=system_prompt,
            persona=persona,
            model_tier=model_tier,  # type: ignore[arg-type]
        )
        return agent.agent_id, agent.model

    agent_id: str
    resolved_model: str
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
        console=console,
    ) as progress:
        progress.add_task(description=f"Deploying agent [bold]{name}[/bold]…", total=None)
        try:
            agent_id, resolved_model = asyncio.run(_run())
        except Exception:  # noqa: BLE001
            console.print_exception()
            raise typer.Exit(code=1)

    console.print(
        Panel(
            f"[bold green]✅ Agent deployed successfully![/bold green]\n\n"
            f"[bold]Name:[/bold]     {name}\n"
            f"[bold]Agent ID:[/bold] {agent_id}\n"
            f"[bold]Model:[/bold]    {resolved_model}\n"
            f"[bold]Persona:[/bold]  {persona}\n"
            f"[bold]Tier:[/bold]     {model_tier}",
            title="[bold cyan]Agent Deployed[/bold cyan]",
            border_style="green",
            padding=(1, 2),
        )
    )


# ---------------------------------------------------------------------------
# ecl audit export
# ---------------------------------------------------------------------------


@app.command()
def audit(
    start: Annotated[
        str | None,
        typer.Option("--start", help="Start date in YYYY-MM-DD format"),
    ] = None,
    end: Annotated[
        str | None,
        typer.Option("--end", help="End date in YYYY-MM-DD format"),
    ] = None,
    output: Annotated[
        Path,
        typer.Option("--output", "-o", help="Output CSV file path"),
    ] = Path("./audit_export.csv"),
) -> None:
    """Export audit log to CSV for compliance reporting."""
    now = datetime.now(tz=UTC)

    try:
        start_dt = (
            datetime.strptime(start, "%Y-%m-%d").replace(tzinfo=UTC)
            if start
            else now - timedelta(days=30)
        )
        end_dt = (
            datetime.strptime(end, "%Y-%m-%d").replace(tzinfo=UTC)
            if end
            else now
        )
    except ValueError as exc:
        err_console.print(f"Invalid date: {exc}  — use YYYY-MM-DD.")
        raise typer.Exit(code=1) from exc

    if start_dt > end_dt:
        err_console.print("--start must be before --end.")
        raise typer.Exit(code=1)

    async def _run() -> int:
        import csv as _csv

        from enterprise_claude.audit import AuditLogger

        audit_log = AuditLogger(db_path=_DEFAULT_AUDIT_DB)
        await audit_log.initialize()
        await audit_log.export_csv(
            start_date=start_dt,
            end_date=end_dt,
            output_path=str(output),
        )
        out = Path(str(output))
        if out.exists():
            with open(out, encoding="utf-8", newline="") as fh:  # noqa: ASYNC230
                return max(0, sum(1 for _ in _csv.reader(fh)) - 1)  # subtract header row
        return 0

    row_count = 0
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
        console=console,
    ) as progress:
        progress.add_task(description="Exporting audit log…", total=None)
        try:
            row_count = asyncio.run(_run())
        except Exception:  # noqa: BLE001
            console.print_exception()
            raise typer.Exit(code=1)

    console.print(
        Panel(
            f"[bold green]✅ Audit export complete![/bold green]\n\n"
            f"[bold]Rows exported:[/bold] {row_count}\n"
            f"[bold]Period:[/bold]       {start_dt.date()} → {end_dt.date()}\n"
            f"[bold]Output:[/bold]       {output.resolve()}",
            title="[bold cyan]Audit Export[/bold cyan]",
            border_style="cyan",
            padding=(1, 2),
        )
    )


# ---------------------------------------------------------------------------
# ecl cost summary
# ---------------------------------------------------------------------------


@app.command()
def cost(
    days: Annotated[
        int,
        typer.Option("--days", "-d", help="Look-back window in days"),
    ] = 7,
) -> None:
    """Show spend breakdown by model and persona."""

    async def _run() -> tuple[Any, Any, dict[str, int], dict[str, int]]:
        import aiosqlite

        from enterprise_claude.token_monitor import MonitorConfig, TokenMonitor

        monitor = TokenMonitor(
            config=MonitorConfig(
                daily_budget_usd=_DEFAULT_BUDGET_USD,
                db_path=_DEFAULT_MONITOR_DB,
            )
        )
        await monitor.initialize()

        now = datetime.now(tz=UTC)
        start_dt = now - timedelta(days=days)
        summary = await monitor.get_cost_summary(start_date=start_dt, end_date=now)
        budget_status = await monitor.check_budget()

        # Per-model and per-persona call counts from audit DB
        model_calls: dict[str, int] = {}
        persona_calls: dict[str, int] = {}
        if Path(_DEFAULT_AUDIT_DB).exists():
            start_iso = start_dt.isoformat()
            async with aiosqlite.connect(_DEFAULT_AUDIT_DB) as db:
                db.row_factory = aiosqlite.Row
                async with db.execute(
                    "SELECT model_used, COUNT(*) AS cnt FROM audit_events "
                    "WHERE timestamp >= ? GROUP BY model_used",
                    (start_iso,),
                ) as cur:
                    async for row in cur:
                        model_calls[row["model_used"]] = row["cnt"]
                async with db.execute(
                    "SELECT persona, COUNT(*) AS cnt FROM audit_events "
                    "WHERE timestamp >= ? GROUP BY persona",
                    (start_iso,),
                ) as cur:
                    async for row in cur:
                        persona_calls[row["persona"]] = row["cnt"]

        return summary, budget_status, model_calls, persona_calls

    try:
        summary, budget_status, model_calls, persona_calls = asyncio.run(_run())
    except Exception:  # noqa: BLE001
        console.print_exception()
        raise typer.Exit(code=1)

    # ── 1. Budget status ──────────────────────────────────────────────────────
    pct = budget_status.pct_used
    bar_width = 38
    filled = int(bar_width * min(pct / 100.0, 1.0))
    empty = bar_width - filled
    if pct < 60:
        bar_color = "green"
    elif pct < 85:
        bar_color = "yellow"
    else:
        bar_color = "red"

    bar = f"[{bar_color}]{'█' * filled}[/{bar_color}]{'░' * empty}"
    budget_lines = [
        f"Daily Budget  {bar}  [{bar_color}]{pct:.1f}%[/{bar_color}]",
        (
            f"[bold]Used:[/bold] ${budget_status.used_usd:.4f}  "
            f"[bold]Budget:[/bold] ${budget_status.budget_usd:.2f}  "
            f"[bold]Remaining:[/bold] ${budget_status.remaining_usd:.4f}"
        ),
    ]
    if budget_status.alert:
        budget_lines.append("\n[bold red]⚠  Budget alert threshold exceeded![/bold red]")

    console.print(
        Panel(
            "\n".join(budget_lines),
            title="[bold cyan]Budget Status (Today)[/bold cyan]",
            border_style=bar_color,
            padding=(1, 2),
        )
    )

    # ── 2. By model ───────────────────────────────────────────────────────────
    model_table = Table(
        title=f"Cost by Model — Last {days} Days",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    model_table.add_column("Model")
    model_table.add_column("Calls", justify="right")
    model_table.add_column("Cost USD", justify="right")

    for model_id, cost_val in sorted(summary.by_model.items(), key=lambda x: -x[1]):
        model_table.add_row(
            model_id,
            str(model_calls.get(model_id, "—")),
            f"${cost_val:.4f}",
        )
    if not summary.by_model:
        model_table.add_row("[dim]No data[/dim]", "—", "—")
    console.print(model_table)

    # ── 3. By persona ─────────────────────────────────────────────────────────
    persona_table = Table(
        title=f"Cost by Persona — Last {days} Days",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    persona_table.add_column("Persona")
    persona_table.add_column("Calls", justify="right")
    persona_table.add_column("Cost USD", justify="right")

    for persona_id, cost_val in sorted(summary.by_persona.items(), key=lambda x: -x[1]):
        persona_table.add_row(
            persona_id,
            str(persona_calls.get(persona_id, "—")),
            f"${cost_val:.4f}",
        )
    if not summary.by_persona:
        persona_table.add_row("[dim]No data[/dim]", "—", "—")
    console.print(persona_table)

    # ── 4. Total summary ──────────────────────────────────────────────────────
    console.print(
        Panel(
            f"[bold]Total Cost:[/bold]    [bold green]${summary.total_usd:.4f}[/bold green] USD\n"
            f"[bold]Total Records:[/bold] {summary.record_count}\n"
            f"[bold]Period:[/bold]        "
            f"{summary.period_start.strftime('%Y-%m-%d')} → {summary.period_end.strftime('%Y-%m-%d')}",
            title=f"[bold cyan]Cost Summary — Last {days} Days[/bold cyan]",
            border_style="cyan",
            padding=(1, 2),
        )
    )


# ---------------------------------------------------------------------------
# ecl waves status
# ---------------------------------------------------------------------------

_STATUS_STYLES: dict[str, str] = {
    "planned": "blue",
    "active": "green",
    "complete": "dim",
    "paused": "yellow",
}

_DEFAULT_WAVES: list[dict[str, Any]] = [
    {
        "id": "wave-1",
        "name": "Pilot",
        "status": "complete",
        "target": 10,
        "activated": 10,
        "start_date": "2025-01-01",
    },
    {
        "id": "wave-2",
        "name": "Early Adopters",
        "status": "active",
        "target": 100,
        "activated": 47,
        "start_date": "2025-03-01",
    },
    {
        "id": "wave-3",
        "name": "General Availability",
        "status": "planned",
        "target": 1000,
        "activated": 0,
        "start_date": "2025-06-01",
    },
]


@app.command()
def waves() -> None:
    """Show wave rollout progress table."""
    wave_data: list[dict[str, Any]] = []

    # 1. Try the real AdoptionTracker module
    try:
        from enterprise_claude.adoption_tracker import AdoptionTracker

        async def _get_waves() -> list[dict[str, Any]]:
            tracker = AdoptionTracker()
            if hasattr(tracker, "initialize"):
                await tracker.initialize()
            raw_waves = tracker.list_waves() if hasattr(tracker, "list_waves") else []
            result: list[dict[str, Any]] = []
            for w in raw_waves:
                result.append(
                    {
                        "id": getattr(w, "wave_id", str(w)),
                        "name": getattr(w, "name", "—"),
                        "status": getattr(w, "status", "planned"),
                        "target": getattr(w, "target_count", "—"),
                        "activated": getattr(w, "activated_count", 0),
                        "start_date": str(getattr(w, "start_date", "—")),
                    }
                )
            return result

        wave_data = asyncio.run(_get_waves())
    except Exception:  # noqa: BLE001, S110
        pass

    # 2. Fall back to ecl_config.yaml
    if not wave_data:
        config_path = Path("ecl_config.yaml")
        if config_path.exists():
            try:
                import yaml

                cfg = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
                for w in cfg.get("waves", []):
                    wave_data.append(
                        {
                            "id": w.get("id", "—"),
                            "name": w.get("name", "—"),
                            "status": w.get("status", "planned"),
                            "target": w.get("target_count", "—"),
                            "activated": w.get("activated_count", 0),
                            "start_date": str(w.get("start_date", "—")),
                        }
                    )
            except Exception:  # noqa: BLE001, S110
                pass

    # 3. Fall back to illustrative defaults
    if not wave_data:
        wave_data = _DEFAULT_WAVES

    table = Table(
        title="Wave Rollout Status",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    table.add_column("Wave ID")
    table.add_column("Name")
    table.add_column("Status")
    table.add_column("Target", justify="right")
    table.add_column("Activated", justify="right")
    table.add_column("Progress", justify="right")
    table.add_column("Start Date")

    for w in wave_data:
        status = str(w.get("status", "planned"))
        style = _STATUS_STYLES.get(status, "white")
        status_text = Text(status, style=style)

        target = w.get("target", 0)
        activated = w.get("activated", 0)
        try:
            pct_val = int(activated) / int(target) * 100
            pct_str = f"{pct_val:.1f}%"
        except (TypeError, ValueError, ZeroDivisionError):
            pct_str = "—"

        table.add_row(
            w.get("id", "—"),
            w.get("name", "—"),
            status_text,
            str(target),
            str(activated),
            pct_str,
            str(w.get("start_date", "—")),
        )

    console.print(table)


# ---------------------------------------------------------------------------
# ecl governance check
# ---------------------------------------------------------------------------


@app.command()
def governance() -> None:
    """Validate current governance configuration and warn about gaps."""
    from enterprise_claude.governance import GovernanceConfig, GovernanceLayer

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")

    # Build config from environment variables
    pii_filter = _bool_env("ECL_PII_FILTER", "true")
    gxp_mode = _bool_env("ECL_GXP_MODE", "false")
    max_prompt = int(os.environ.get("ECL_MAX_PROMPT_LENGTH", "100000"))
    require_sys = _bool_env("ECL_REQUIRE_SYSTEM_PROMPT", "true")
    constitutional = _bool_env("ECL_CONSTITUTIONAL_AI", "true")
    blocked_raw = os.environ.get("ECL_BLOCKED_KEYWORDS", "")
    blocked_kw: list[str] = [k.strip() for k in blocked_raw.split(",") if k.strip()]

    cfg = GovernanceConfig(
        pii_filter=pii_filter,
        gxp_mode=gxp_mode,
        max_prompt_length=max_prompt,
        require_system_prompt=require_sys,
        constitutional_ai=constitutional,
        blocked_keywords=blocked_kw,
    )
    # Instantiate the layer to confirm it initialises cleanly
    _layer = GovernanceLayer(config=cfg)

    def _row(label: str, enabled: bool, warn_if_off: bool = True) -> str:
        if enabled:
            return f"[bold green]✅[/bold green]  {label}"
        elif warn_if_off:
            return f"[bold yellow]⚠[/bold yellow]   {label} [dim](disabled)[/dim]"
        else:
            return f"[dim]—   {label} (disabled)[/dim]"

    kw_note: str
    if not blocked_kw:
        kw_note = " [yellow](none — consider adding topic-specific terms)[/yellow]"
    elif len(blocked_kw) <= 3:
        kw_note = f" ({', '.join(blocked_kw)})"
    else:
        kw_note = f" ({', '.join(blocked_kw[:3])}, …+{len(blocked_kw) - 3} more)"

    settings_lines = [
        "[bold]Feature flags:[/bold]\n",
        _row("PII Filter", cfg.pii_filter),
        _row("GxP / Regulatory Mode", cfg.gxp_mode, warn_if_off=False),
        _row("Require System Prompt", cfg.require_system_prompt),
        _row("Constitutional AI", cfg.constitutional_ai),
        _row("Log Violations", cfg.log_violations),
        "",
        f"[bold]Max Prompt Length:[/bold]  {cfg.max_prompt_length:,} chars",
        f"[bold]Blocked Keywords:[/bold]   {len(blocked_kw)} configured{kw_note}",
    ]

    # Collect warnings
    warnings: list[str] = []
    if not api_key:
        warnings.append("[bold red]⚠  ANTHROPIC_API_KEY is not set[/bold red]")
    if not cfg.pii_filter:
        warnings.append(
            "[yellow]⚠  PII filter disabled — sensitive data may appear in logs[/yellow]"
        )
    if not cfg.require_system_prompt:
        warnings.append(
            "[yellow]⚠  System prompt not required — agents may behave unpredictably[/yellow]"
        )
    if not blocked_kw:
        warnings.append("[yellow]⚠  No blocked keywords configured[/yellow]")

    if warnings:
        settings_lines.append("\n[bold]Warnings:[/bold]")
        settings_lines.extend(warnings)
        border = "yellow"
    else:
        settings_lines.append("\n[bold green]✅ Configuration looks healthy![/bold green]")
        border = "green"

    console.print(
        Panel(
            "\n".join(settings_lines),
            title="[bold cyan]Governance Configuration[/bold cyan]",
            border_style=border,
            padding=(1, 2),
        )
    )


# ---------------------------------------------------------------------------
# ecl connectors list
# ---------------------------------------------------------------------------


@app.command()
def connectors() -> None:
    """List available MCP connectors and their configuration status."""
    registry: list[dict[str, Any]] = []

    # Try the real MCPConnectorRegistry first
    try:
        from enterprise_claude.mcp_connectors import list_connectors

        raw = list_connectors()
        for c in raw:
            registry.append(
                {
                    "name": getattr(c, "name", str(c)),
                    "description": getattr(c, "description", ""),
                    "auth_type": getattr(c, "auth_type", "—"),
                    "required_env": list(getattr(c, "required_env", [])),
                    "tags": list(getattr(c, "tags", [])),
                }
            )
    except Exception:  # noqa: BLE001
        registry = _CONNECTOR_REGISTRY

    table = Table(
        title="MCP Connector Registry",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
    )
    table.add_column("Connector", style="bold")
    table.add_column("Description", max_width=38)
    table.add_column("Auth Type")
    table.add_column("Required Env Vars", max_width=36)
    table.add_column("Status", justify="center")

    for c in registry:
        required_env: list[str] = c.get("required_env", [])
        all_set = all(bool(os.environ.get(v)) for v in required_env)
        status_text = Text("✅", style="green") if all_set else Text("❌", style="red")

        # Colour individual env-var names by whether they are set
        env_cell = Text()
        for i, var in enumerate(required_env):
            colour = "green" if os.environ.get(var) else "red"
            env_cell.append(var, style=colour)
            if i < len(required_env) - 1:
                env_cell.append("\n")

        tags = c.get("tags", [])
        name_with_tags = Text(c.get("name", ""))
        if tags:
            name_with_tags.append(f"\n{' '.join('#' + t for t in tags)}", style="dim")

        table.add_row(
            name_with_tags,
            c.get("description", ""),
            c.get("auth_type", "—"),
            env_cell,
            status_text,
        )

    console.print(table)

    configured = sum(
        1
        for c in registry
        if all(bool(os.environ.get(v)) for v in c.get("required_env", []))
    )
    total = len(registry)
    suffix = (
        "  Run [bold]ecl init[/bold] to scaffold a .env.example with all required vars."
        if configured < total
        else ""
    )
    console.print(f"\n[dim]{configured}/{total} connectors fully configured.[/dim]{suffix}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app()
